# Generated by Django 5.2.10 on 2026-04-23 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('series', models.CharField(blank=True, max_length=10, null=True)),
                ('isin_code', models.CharField(blank=True, max_length=20, null=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='core.sector')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('quarter', models.CharField(blank=True, max_length=2, null=True)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_assets', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_liabilities', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('operating_cash_flow', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('roe', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('debt_to_equity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('opm', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pe_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='core.company')),
            ],
            options={
                'unique_together': {('company', 'year', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='MLFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('health_score', models.IntegerField(default=0)),
                ('anomaly_status', models.BooleanField(default=False)),
                ('anomaly_description', models.TextField(blank=True, null=True)),
                ('cluster_group', models.IntegerField(default=0)),
                ('revenue_forecast', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('last_computed', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_insights', to='core.company')),
            ],
            options={
                'unique_together': {('company', 'year')},
            },
        ),
    ]
