# Generated by Django 5.2.10 on 2026-05-30 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='about_company',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='book_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='company',
            name='bse_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='chart_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='face_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='company',
            name='nse_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='roce',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='company',
            name='roe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='financialfact',
            name='depreciation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='financialfact',
            name='dividend_payout',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='financialfact',
            name='eps',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='financialfact',
            name='expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='financialfact',
            name='interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='financialfact',
            name='is_ttm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialfact',
            name='month',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='financialfact',
            name='operating_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='financialfact',
            name='opm_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='financialfact',
            name='other_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='financialfact',
            name='profit_before_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='financialfact',
            name='sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='financialfact',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mlfact',
            name='auto_cons',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlfact',
            name='auto_pros',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlfact',
            name='cashflow_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='mlfact',
            name='dividend_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='mlfact',
            name='growth_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='mlfact',
            name='health_label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mlfact',
            name='leverage_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='mlfact',
            name='profitability_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='mlfact',
            name='trend_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='sector',
            name='sector_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='financialfact',
            name='quarter',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='ProsCons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pros', models.TextField(blank=True, null=True)),
                ('cons', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pros_cons', to='core.company')),
            ],
            options={
                'verbose_name_plural': 'Pros and Cons',
            },
        ),
        migrations.CreateModel(
            name='AnalysisFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_facts', to='core.company')),
            ],
            options={
                'unique_together': {('company', 'metric', 'period')},
            },
        ),
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.CharField(blank=True, max_length=10, null=True)),
                ('is_ttm', models.BooleanField(default=False)),
                ('equity_capital', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('reserves', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('borrowings', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('other_liabilities', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_liabilities', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('fixed_assets', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('cwip', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('investments', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('other_assets', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_assets', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_sheets', to='core.company')),
            ],
            options={
                'unique_together': {('company', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.CharField(blank=True, max_length=10, null=True)),
                ('is_ttm', models.BooleanField(default=False)),
                ('operating_activity', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('investing_activity', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('financing_activity', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('net_cash_flow', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flows', to='core.company')),
            ],
            options={
                'unique_together': {('company', 'year', 'month')},
            },
        ),
    ]
